<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-RestaurantBookingSystem-037d91d8-515a-4cc7-bc9e-3421a1220d5d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.23" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestaurantBookingSystem.Data.Models\RestaurantBookingSystem.Data.Models.csproj" />
    <ProjectReference Include="..\RestaurantBookingSystem.Data\RestaurantBookingSystem.Data.csproj" />
    <ProjectReference Include="..\RestaurantBookingSystem.GCommon\RestaurantBookingSystem.GCommon.csproj" />
    <ProjectReference Include="..\RestaurantBookingSystem.Services\RestaurantBookingSystem.Services.csproj" />
    <ProjectReference Include="..\RestaurantBookingSystem.ViewModels\RestaurantBookingSystem.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Controllers\" />
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Admin\Views\" />
  </ItemGroup>

</Project>
